import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Roboto } from "next/font/google";
import LenisProvider from "@/components/ui/Scroll Wrapper/LenisProvider";
import "animate.css";
import { AuthProvider } from "@/core/context/AuthContext";
import MobileNav from "@/components/MobileNav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // pick the weights you need
  variable: "--font-roboto", // optional for CSS variable
});
console.log("test");

export const metadata: Metadata = {
  title: "Investors Portal - InsureCow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider>
          <MobileNav />
          <div className="hidden lg:block">
            <Navbar />
          </div>
          <div>
            <LenisProvider>{children}</LenisProvider>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
